# Generated by Django 4.2.7 on 2025-09-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
    ]
