# Generated by Django 4.2.7 on 2025-09-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dress_details',
        ),
        migrations.AddField(
            model_name='event',
            name='event_reason',
            field=models.TextField(blank=True, help_text='Reason or purpose of the event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='participation_type',
            field=models.CharField(blank=True, help_text='Type of participation (e.g., Recitation, Listening, etc.)', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Dress requirement description', max_length=200)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of dress detail in event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Event this dress detail belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dress_details', to='events.event')),
            ],
            options={
                'verbose_name': 'Dress Detail',
                'verbose_name_plural': 'Dress Details',
                'db_table': 'dress_details',
                'ordering': ['event', 'order'],
                'unique_together': {('event', 'order')},
            },
        ),
    ]
